#!/bin/sh

pwd=$(pwd)
cd $(dirname $0)/../lib
db=$(basename $(dirname $(pwd)))
mkdir -p QI/Schema/Result QI/Schema/ResultSet
# -o constraint='qr/^[^(rotarians)]$/' # Rotarian.pm was needing to be custom for has_submission
# sub { warn "$_[0]\n"; return "_$_[1]" if grep { @o=split /\./; warn "$_ -- $o[0] eq $_[2]->{table_name} && $o[1] eq $_[1]\n"; $o[0] eq $_[2]->{table_name} && $o[1] eq $_[1] } qw/rotarians.has_submissions/; return undef; };
# -o components='["InflateColumn::DateTime", "Helper::Row::ToJSON"]'
# -o col_accessor_map='sub { return "_$_[1]" if $_[2]->{table_name} eq "rotarians" && grep { $_ eq $_[1] } qw/has_submissions/; return undef; }' \
# -o result_base_class='QI::Schema::Result' \
dbicdump \
	-o dump_directory=. \
	-o default_resultset_class=ResultSet \
	-o preserve_case=1 \
	-o result_base_class='QI::Schema::Result' \
	QI::Schema dbi:mysql:database=${1:-$db} ${2:-$db} ${3:-$db} '{ quote_char => "`" }'
